/**
 * This class is generated by jOOQ
 */
package com.worksap.stm2016.jooq.domain;


import com.worksap.stm2016.jooq.domain.tables.CheckAttendance;
import com.worksap.stm2016.jooq.domain.tables.CheckPerformance;
import com.worksap.stm2016.jooq.domain.tables.CheckSkill;
import com.worksap.stm2016.jooq.domain.tables.InfoAccount;
import com.worksap.stm2016.jooq.domain.tables.InfoDepartment;
import com.worksap.stm2016.jooq.domain.tables.InfoFte;
import com.worksap.stm2016.jooq.domain.tables.InfoSte;
import com.worksap.stm2016.jooq.domain.tables.RecruitAgency;
import com.worksap.stm2016.jooq.domain.tables.RecruitApplyment;
import com.worksap.stm2016.jooq.domain.tables.RecruitApplymentLog;
import com.worksap.stm2016.jooq.domain.tables.RecruitInterview;
import com.worksap.stm2016.jooq.domain.tables.RecruitPool;
import com.worksap.stm2016.jooq.domain.tables.RecruitPoolLog;
import com.worksap.stm2016.jooq.domain.tables.RecruitPosition;
import com.worksap.stm2016.jooq.domain.tables.RecruitPositionLog;
import com.worksap.stm2016.jooq.domain.tables.RecruitPublished;
import com.worksap.stm2016.jooq.domain.tables.SnsMessage;
import com.worksap.stm2016.jooq.domain.tables.SnsTimeline;
import com.worksap.stm2016.jooq.domain.tables.StaffingChange;
import com.worksap.stm2016.jooq.domain.tables.StaffingChangeLog;
import com.worksap.stm2016.jooq.domain.tables.TestComments;
import com.worksap.stm2016.jooq.domain.tables.TestPosts;
import com.worksap.stm2016.jooq.domain.tables.ViRecruitApplymentHistory;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in ss1604c195_rd4
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table ss1604c195_rd4.check_attendance
	 */
	public static final CheckAttendance CHECK_ATTENDANCE = com.worksap.stm2016.jooq.domain.tables.CheckAttendance.CHECK_ATTENDANCE;

	/**
	 * The table ss1604c195_rd4.check_performance
	 */
	public static final CheckPerformance CHECK_PERFORMANCE = com.worksap.stm2016.jooq.domain.tables.CheckPerformance.CHECK_PERFORMANCE;

	/**
	 * The table ss1604c195_rd4.check_skill
	 */
	public static final CheckSkill CHECK_SKILL = com.worksap.stm2016.jooq.domain.tables.CheckSkill.CHECK_SKILL;

	/**
	 * The table ss1604c195_rd4.info_account
	 */
	public static final InfoAccount INFO_ACCOUNT = com.worksap.stm2016.jooq.domain.tables.InfoAccount.INFO_ACCOUNT;

	/**
	 * The table ss1604c195_rd4.info_department
	 */
	public static final InfoDepartment INFO_DEPARTMENT = com.worksap.stm2016.jooq.domain.tables.InfoDepartment.INFO_DEPARTMENT;

	/**
	 * The table ss1604c195_rd4.info_fte
	 */
	public static final InfoFte INFO_FTE = com.worksap.stm2016.jooq.domain.tables.InfoFte.INFO_FTE;

	/**
	 * The table ss1604c195_rd4.info_ste
	 */
	public static final InfoSte INFO_STE = com.worksap.stm2016.jooq.domain.tables.InfoSte.INFO_STE;

	/**
	 * The table ss1604c195_rd4.recruit_agency
	 */
	public static final RecruitAgency RECRUIT_AGENCY = com.worksap.stm2016.jooq.domain.tables.RecruitAgency.RECRUIT_AGENCY;

	/**
	 * The table ss1604c195_rd4.recruit_applyment
	 */
	public static final RecruitApplyment RECRUIT_APPLYMENT = com.worksap.stm2016.jooq.domain.tables.RecruitApplyment.RECRUIT_APPLYMENT;

	/**
	 * The table ss1604c195_rd4.recruit_applyment_log
	 */
	public static final RecruitApplymentLog RECRUIT_APPLYMENT_LOG = com.worksap.stm2016.jooq.domain.tables.RecruitApplymentLog.RECRUIT_APPLYMENT_LOG;

	/**
	 * The table ss1604c195_rd4.recruit_interview
	 */
	public static final RecruitInterview RECRUIT_INTERVIEW = com.worksap.stm2016.jooq.domain.tables.RecruitInterview.RECRUIT_INTERVIEW;

	/**
	 * The table ss1604c195_rd4.recruit_pool
	 */
	public static final RecruitPool RECRUIT_POOL = com.worksap.stm2016.jooq.domain.tables.RecruitPool.RECRUIT_POOL;

	/**
	 * The table ss1604c195_rd4.recruit_pool_log
	 */
	public static final RecruitPoolLog RECRUIT_POOL_LOG = com.worksap.stm2016.jooq.domain.tables.RecruitPoolLog.RECRUIT_POOL_LOG;

	/**
	 * The table ss1604c195_rd4.recruit_position
	 */
	public static final RecruitPosition RECRUIT_POSITION = com.worksap.stm2016.jooq.domain.tables.RecruitPosition.RECRUIT_POSITION;

	/**
	 * The table ss1604c195_rd4.recruit_position_log
	 */
	public static final RecruitPositionLog RECRUIT_POSITION_LOG = com.worksap.stm2016.jooq.domain.tables.RecruitPositionLog.RECRUIT_POSITION_LOG;

	/**
	 * The table ss1604c195_rd4.recruit_published
	 */
	public static final RecruitPublished RECRUIT_PUBLISHED = com.worksap.stm2016.jooq.domain.tables.RecruitPublished.RECRUIT_PUBLISHED;

	/**
	 * The table ss1604c195_rd4.sns_message
	 */
	public static final SnsMessage SNS_MESSAGE = com.worksap.stm2016.jooq.domain.tables.SnsMessage.SNS_MESSAGE;

	/**
	 * The table ss1604c195_rd4.sns_timeline
	 */
	public static final SnsTimeline SNS_TIMELINE = com.worksap.stm2016.jooq.domain.tables.SnsTimeline.SNS_TIMELINE;

	/**
	 * The table ss1604c195_rd4.staffing_change
	 */
	public static final StaffingChange STAFFING_CHANGE = com.worksap.stm2016.jooq.domain.tables.StaffingChange.STAFFING_CHANGE;

	/**
	 * The table ss1604c195_rd4.staffing_change_log
	 */
	public static final StaffingChangeLog STAFFING_CHANGE_LOG = com.worksap.stm2016.jooq.domain.tables.StaffingChangeLog.STAFFING_CHANGE_LOG;

	/**
	 * The table ss1604c195_rd4.test_comments
	 */
	public static final TestComments TEST_COMMENTS = com.worksap.stm2016.jooq.domain.tables.TestComments.TEST_COMMENTS;

	/**
	 * The table ss1604c195_rd4.test_posts
	 */
	public static final TestPosts TEST_POSTS = com.worksap.stm2016.jooq.domain.tables.TestPosts.TEST_POSTS;

	/**
	 * The table ss1604c195_rd4.vi_recruit_applyment_history
	 */
	public static final ViRecruitApplymentHistory VI_RECRUIT_APPLYMENT_HISTORY = com.worksap.stm2016.jooq.domain.tables.ViRecruitApplymentHistory.VI_RECRUIT_APPLYMENT_HISTORY;
}
