/**
 * This class is generated by jOOQ
 */
package com.worksap.stm2016.jooq.domain.tables;


import com.worksap.stm2016.jooq.domain.Keys;
import com.worksap.stm2016.jooq.domain.Ss1604c195Rd4;
import com.worksap.stm2016.jooq.domain.tables.records.RecruitPublishedRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.7.2"
	},
	comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RecruitPublished extends TableImpl<RecruitPublishedRecord> {

	private static final long serialVersionUID = 876953992;

	/**
	 * The reference instance of <code>ss1604c195_rd4.recruit_published</code>
	 */
	public static final RecruitPublished RECRUIT_PUBLISHED = new RecruitPublished();

	/**
	 * The class holding records for this type
	 */
	@Override
	public Class<RecruitPublishedRecord> getRecordType() {
		return RecruitPublishedRecord.class;
	}

	/**
	 * The column <code>ss1604c195_rd4.recruit_published.publishedid</code>.
	 */
	public final TableField<RecruitPublishedRecord, Integer> PUBLISHEDID = createField("publishedid", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>ss1604c195_rd4.recruit_published.poolid</code>.
	 */
	public final TableField<RecruitPublishedRecord, Integer> POOLID = createField("poolid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>ss1604c195_rd4.recruit_published.agencyid</code>.
	 */
	public final TableField<RecruitPublishedRecord, Integer> AGENCYID = createField("agencyid", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>ss1604c195_rd4.recruit_published</code> table reference
	 */
	public RecruitPublished() {
		this("recruit_published", null);
	}

	/**
	 * Create an aliased <code>ss1604c195_rd4.recruit_published</code> table reference
	 */
	public RecruitPublished(String alias) {
		this(alias, RECRUIT_PUBLISHED);
	}

	private RecruitPublished(String alias, Table<RecruitPublishedRecord> aliased) {
		this(alias, aliased, null);
	}

	private RecruitPublished(String alias, Table<RecruitPublishedRecord> aliased, Field<?>[] parameters) {
		super(alias, Ss1604c195Rd4.SS1604C195_RD4, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Identity<RecruitPublishedRecord, Integer> getIdentity() {
		return Keys.IDENTITY_RECRUIT_PUBLISHED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UniqueKey<RecruitPublishedRecord> getPrimaryKey() {
		return Keys.RECRUIT_PUBLISHED_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public List<UniqueKey<RecruitPublishedRecord>> getKeys() {
		return Arrays.<UniqueKey<RecruitPublishedRecord>>asList(Keys.RECRUIT_PUBLISHED_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RecruitPublished as(String alias) {
		return new RecruitPublished(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RecruitPublished rename(String name) {
		return new RecruitPublished(name, null);
	}
}
